kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-fs
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume-fs
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo `date` >> /data/temp_dir.txt; sleep 10;done"]
  volumes:
    - name: my-csi-volume-fs
      persistentVolumeClaim:
        claimName: pvc-wekafs-fs # defined in pvc-wekafs-fs.yaml