apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wekafs-dir-static
  namespace: csi-wekafs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storageclass-wekafs-dir 
  volumeMode: Filesystem
  volumeName: pv-wekafs-dir-static
  resources:
    requests:
      storage: 1Gi
